name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 11 * * *' # Ejecutar todos los días a las 8 am (hora de Chile, UTC-3)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npm run test-report

  # Enviar el reporte por correo electrónico
      - name: Send Email with Mocha Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          body: |
            ¡Hola!

            Se adjunta el archivo con los resultados de las pruebas de Cypress ejecutadas en el pipeline.

            ¡Saludos!
          to: "testingpipeline2024@gmail.com"  
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: "mocha-report/mochawesome.html"

     #     Depurar el contexto de GitHub para verificar la URL del pipeline
      - name: Debug GitHub Context
        run: echo "Pipeline URL:'"${{ github.run_url }}"'"
        
     # Notificar a Slack
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ *Pipeline Ejecutado*",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "Detalles del Pipeline",
                "title_link": "'"${{ github.run_url }}"'",
                "text": "El pipeline se ha ejecutado correctamente. Puedes ver más detalles en el enlace de abajo.",
                "footer": "GitHub Actions",
                "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                "ts": '$(date +%s)'
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
