name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 11 * * *' # Ejecutar todos los días a las 8 am (hora de Chile, UTC-3)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npm run test-report

  # Enviar el reporte por correo electrónico
      - name: Send Email with Mocha Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          body: "Adjunto encontrarás el reporte de las pruebas."
          to: "testingpipeline2024@gmail.com"  
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: "cypressTest/mocha-report/mochawesome.html"  
