name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 11 * * *' # Ejecutar todos los días a las 8 am (hora de Chile, UTC-3)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npm run test-report

# Leer el reporte HTML generado
      - name: Read HTML Report
        id: read_report
        run: |
          REPORT=$(cat mocha-report/mochawesome.html)
          echo "HTML_REPORT<<EOF" >> $GITHUB_ENV
          echo "$REPORT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  # Enviar el reporte por correo electrónico
      - name: Send Email with Mocha Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          body: >
            <!DOCTYPE html>
            <html>
            <head>
              <style>
                body { font-family: Arial, sans-serif; }
                h1 { color: #333; }
                p { color: #555; }
              </style>
            </head>
            <body>
              <h1>Reporte de Pruebas de Cypress</h1>
              <p>El reporte de las pruebas de Cypress generadas está disponible a continuación:</p>
              <div>
                ${{ env.HTML_REPORT }}  <!-- Incrustar el HTML directamente aquí -->
              </div>
              <p>Si tienes algún problema abriendo el reporte, por favor avísanos.</p>
              <p>¡Saludos!</p>
            </body>
            </html>
          to: "testingpipeline2024@gmail.com"  
          from: ${{ secrets.SMTP_USERNAME }}
