name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 11 * * *' # Ejecutar todos los días a las 8 am (hora de Chile, UTC-3)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npm run test-report

 # Comprimir la carpeta mocha-report en formato tar.gz
      - name: Compress mocha-report directory to tar.gz
        run: |
          tar -czf mocha-report.tar.gz mocha-report

  # Enviar el reporte por correo electrónico
      - name: Send Email with Mocha Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          body: |
            ¡Hola!

            Adjuntamos el reporte de las pruebas de Cypress generadas.

            Para ver los resultados de las pruebas, por favor sigue estos pasos:

            1. **Descarga el archivo adjunto** llamado `mocha-report.zip`.
            2. **Descomprime el archivo** en tu computadora.
            3. Abre el archivo `mochawesome.html` en tu navegador web (como Chrome, Firefox o Safari).
            4. El reporte se mostrará como una página web interactiva con los resultados de las pruebas.

            Si tienes algún problema abriendo el reporte, por favor avísanos.

            ¡Saludos!
          to: "testingpipeline2024@gmail.com"  
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: "mocha-report.tar.gz" 
