name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 11 * * *' # Ejecutar todos los días a las 8 am (hora de Chile, UTC-3)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npm run test-report

# Leer el reporte HTML generado y enviarlo en el correo
      - name: Read HTML Report
        id: read_report
        run: |
          REPORT=$(cat mocha-report/mochawesome.html)
          echo "::set-output name=html_report::$REPORT"

  # Enviar el reporte por correo electrónico
      - name: Send Email with Mocha Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          body: |
            ¡Hola!

            El reporte de las pruebas de Cypress generadas está disponible a continuación:

            ${{ steps.read_report.outputs.html_report }}  # Incrustar el HTML directamente en el correo

            Si tienes algún problema abriendo el reporte, por favor avísanos.

            ¡Saludos!
          to: "testingpipeline2024@gmail.com"  
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: "mocha-report.tar.gz" 
