name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 11 * * *' # Run every day at 8am (Chile time, UTC-3)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npm run test-report

  # Send the report by email
      - name: Send Email with Mocha Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Cypress Test Report"
          body: |
            Hello!

              In this email is attached a .html file, which you must download, and then in your download folder click on it and it will open in your browser to view it.

            Regards!
          to: "testingpipeline2024@gmail.com"  
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: "mocha-report/index.html"

     # Building the Pipeline URL
      - name: Build Pipeline URL
        run: |
          PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Pipeline URL: $PIPELINE_URL"
          echo "PIPELINE_URL=$PIPELINE_URL" >> $GITHUB_ENV
        
     # Notify Slack
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ *Pipeline Executed*",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "Pipeline Details",
                "title_link": "'"${{ env.PIPELINE_URL }}"'",
                "text": "The pipeline has been executed successfully. Click the link for more details..",
                "footer": "GitHub Actions",
                "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                "ts": '$(date +%s)'
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
